[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[environment]
# Improve build performance
NODE_OPTIONS = "--max-old-space-size=4096"
